/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: shawn0172181 (https://sketchfab.com/shawn0172181)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pant-detailed-sewing-for-factory-396c9131c4124e269ec0d44a40b33540
Title: Pant detailed sewing for factory
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useSnapshot } from 'valtio'
import { state } from '../store/Index'
import { easing } from 'maath'
import { useTexture } from '@react-three/drei'
import { Decal } from '@react-three/drei'

export function Scene({stat},props) {
  const snap=useSnapshot(state);
  const { nodes, materials } = useGLTF('/scene.gltf')
  const pant=useRef()
  console.log(stat)
  const [rot,setRot]=useState(stat)

  useFrame(()=>((snap.pant_active)?pant.current.rotation.y+=0.01:<></>))
  useFrame((state, delta) =>{ 
    easing.dampC(materials.Default_Fabric_FRONT_3741.color, snap.pant_color, 0.25, delta)
    easing.dampC(materials.Material3839.color, snap.pant_color, 0.25, delta)
  });
  const fullTexture = useTexture(snap.fullDecalP);
  return (
    <group {...props} dispose={null} ref={pant}
    onClick={()=>{
      setRot(!rot)
    }}>
      <mesh geometry={nodes.pant_2_Default_Fabric_FRONT_3741_0.geometry} material={materials.Default_Fabric_FRONT_3741} >
      {snap.isFullTextureP && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.pant_2_Material3839_0.geometry} material={materials.Material3839} >
      {snap.isFullTextureP && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.pant_2_Material3835_0.geometry} material={materials.Material3835} />
      <mesh geometry={nodes.pant_2_Material3847_0.geometry} material={materials.Material3847} />
      <mesh geometry={nodes.pant_2_Material3987_0.geometry} material={materials.Material3987} />
      <mesh geometry={nodes.pant_2_Material22071_0.geometry} material={materials.Material22071} />
      <mesh geometry={nodes.pant_2_Material4803_0.geometry} material={materials.Material4803} />
      <mesh geometry={nodes.pant_2_Material4803_0_1.geometry} material={materials.Material4803} />
      <mesh geometry={nodes.pant_2_Material4635_0.geometry} material={materials.Material4635} />
      <mesh geometry={nodes.pant_2_Material4716_0.geometry} material={materials.Material4716} />
      <mesh geometry={nodes.pant_2_Material4068_0.geometry} material={materials.Material4068} />
      <mesh geometry={nodes.pant_2_Material4149_0.geometry} material={materials.Material4149} />
      <mesh geometry={nodes.pant_2_Material4392_0.geometry} material={materials.Material4392} />
      <mesh geometry={nodes.pant_2_Material3869_0.geometry} material={materials.Material3869} />
      <mesh geometry={nodes.pant_2_Material4473_0.geometry} material={materials.Material4473} />
      <mesh geometry={nodes.pant_2_Material4554_0.geometry} material={materials.Material4554} />
      <mesh geometry={nodes.pant_2_Material4230_0.geometry} material={materials.Material4230} />
      <mesh geometry={nodes.pant_2_Material4311_0.geometry} material={materials.Material4311} />
      <mesh geometry={nodes.pant_2_Material5127_0.geometry} material={materials.Material5127} />
      <mesh geometry={nodes.pant_2_Material5127_0_1.geometry} material={materials.Material5127} />
      <mesh geometry={nodes.pant_2_Material5209_0.geometry} material={materials.Material5209} />
      <mesh geometry={nodes.pant_2_Material5209_0_1.geometry} material={materials.Material5209} />
      <mesh geometry={nodes.pant_2_Material5209_0_2.geometry} material={materials.Material5209} />
      <mesh geometry={nodes.pant_2_Material5209_0_3.geometry} material={materials.Material5209} />
      <mesh geometry={nodes.pant_2_Material5296_0.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_1.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_2.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_3.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_4.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_5.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5296_0_6.geometry} material={materials.Material5296} />
      <mesh geometry={nodes.pant_2_Material5379_0.geometry} material={materials.Material5379} />
      <mesh geometry={nodes.pant_2_Material5046_0.geometry} material={materials.Material5046} />
      <mesh geometry={nodes.pant_2_Material4884_0.geometry} material={materials.Material4884} />
      <mesh geometry={nodes.pant_2_Material4965_0.geometry} material={materials.Material4965} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
