/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { easing } from 'maath';
import { useSnapshot } from 'valtio';
import { state } from '../store/Index';
import { useState } from 'react';
import { useTexture } from '@react-three/drei';
import { Decal } from '@react-three/drei';

export function Shoe({stat},props) {
  const { nodes, materials } = useGLTF('/shoe.gltf')
  const snap=useSnapshot(state)
  const [rot,setRot]=useState(stat);
  const fullTexture = useTexture(snap.fullDecalS);

  const shoe=useRef();
  useFrame(()=>((snap.shoe_active)?shoe.current.rotation.y+=0.01:console.log("Its on focus")))
  useFrame((state, delta) => easing.dampC(materials.mesh.color, snap.color_shoe, 0.25, delta));
  return (
    <group {...props} dispose={null} ref={shoe}
    onClick={()=>{
      setRot(!rot)
    }}>
      <mesh geometry={nodes.shoe.geometry} material={materials.laces} >
      {snap.isFullTextureS && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} >
      </mesh>
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} >
      {snap.isFullTextureS && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.shoe_3.geometry} material={materials.inner} />
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} >
        
      </mesh>
      <mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} >
      {snap.isFullTextureS && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.shoe_6.geometry} material={materials.band} >
      {snap.isFullTextureS && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
      <mesh geometry={nodes.shoe_7.geometry} material={materials.patch} >
      {snap.isFullTextureS && (
            <Decal 
              position={[0, 0, 0]}
              rotation={[0, 0, 0]}
              scale={1}
              map={fullTexture}
            />
          )}
      </mesh>
    </group>
  )
}

useGLTF.preload('/shoe.gltf')
